# Generated by Django 4.2.18 on 2026-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cpf', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome:', max_length=70)),
                ('endereco', models.CharField(help_text='Informe o endereço:', max_length=100)),
                ('telefone', models.IntegerField(help_text='Informe o Telefone:')),
                ('uf', models.CharField(help_text='Informe o UF:', max_length=2)),
                ('cidade', models.CharField(help_text='Informe a cidade:', max_length=50)),
                ('genero', models.CharField(help_text='Informe o gênero:', max_length=1)),
                ('contato', models.CharField(help_text='Informe a forma de contato:', max_length=1)),
                ('email', models.CharField(help_text='Informe o E-mail:', max_length=100, null=True)),
                ('senha', models.CharField(help_text='Informe a senha:', max_length=256)),
            ],
        ),
    ]
