# Generated by Django 4.2.18 on 2026-07-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='custom_salt',
            field=models.CharField(default=0, help_text='Salt gerado', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(choices=[('C', 'Carta'), ('E', 'E-mail'), ('T', 'Telefone'), ('F', 'Fax')], help_text='Informe a forma de contato:', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Informe o gênero:', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Informe o Telefone:', max_length=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(choices=[('rj', 'RJ'), ('sp', 'SP'), ('mg', 'MG'), ('es', 'ES'), ('pr', 'PR'), ('ba', 'BA'), ('rs', 'RS')], help_text='Informe o UF:', max_length=2),
        ),
    ]
