# Generated by Django 4.2.18 on 2026-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fabricante',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do fabricante:', max_length=70)),
            ],
        ),
    ]
