# Generated by Django 4.2.18 on 2026-06-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
