# Generated by Django 4.2.18 on 2026-07-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0002_alter_fabricante_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='desativado',
            field=models.BooleanField(default=False),
        ),
    ]
