# Generated by Django 4.2.18 on 2026-06-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabricante', '0002_alter_fabricante_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do produto:', max_length=70)),
                ('preco_compra', models.FloatField(help_text='Informe o valor de compra:')),
                ('preco_venda', models.FloatField(help_text='Informe o valor de venda:')),
                ('cor', models.CharField(help_text='Informe o nome do produto:', max_length=70)),
                ('imagem', models.CharField(help_text='Informe o nome do produto:', max_length=70)),
                ('fabricante_codigo', models.ForeignKey(help_text='Informe o fabricante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabricante.fabricante')),
            ],
        ),
    ]
