# Generated by Django 4.2.18 on 2026-06-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(help_text='Informe a cor do produto:', max_length=70),
        ),
    ]
