# Generated by Django 4.2.18 on 2026-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(choices=[('azul', 'Azul'), ('vermelho', 'Vermelho'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('preto', 'Preto'), ('marrom', 'Marrom')], default='preto', help_text='Informe a cor do produto:', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(help_text='Informe o nome do produto:', max_length=25),
        ),
    ]
