# Generated by Django 4.2.18 on 2026-07-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_cor_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desativado',
            field=models.BooleanField(default=False),
        ),
    ]
